package model

type ErrorType string

const (
	// Common
	ERROR_UNKNOWN ErrorType = "ERROR_UNKNOWN"

	// Todos
	ERROR_CREATE_TODO_PAYLOAD_IS_INVALID ErrorType = "ERROR_CREATE_TODO_PAYLOAD_IS_INVALID"
	ERROR_CREATE_TODO_FAILED             ErrorType = "ERROR_CREATE_TODO_FAILED"
	ERROR_PATCH_TODO_PAYLOAD_IS_INVALID  ErrorType = "ERROR_PATCH_TODO_PAYLOAD_IS_INVALID"
	ERROR_NO_VALUE_IN_PATCH_TODO_PAYLOAD ErrorType = "ERROR_NO_VALUE_IN_PATCH_TODO_PAYLOAD"
	ERROR_PATCH_TODO_FAILED              ErrorType = "ERROR_PATCH_TODO_FAILED"
	ERROR_GET_CREATED_TODO_FAILED        ErrorType = "ERROR_GET_CREATED_TODO_FAILED"
	ERROR_GET_PATCHED_TODO_FAILED        ErrorType = "ERROR_GET_PATCHED_TODO_FAILED"
	ERROR_DELETE_TODO_NOT_EXIST          ErrorType = "ERROR_DELETE_TODO_NOT_EXIST"
	ERROR_DELETE_TODO_FAILED             ErrorType = "ERROR_DELETE_TODO_FAILED"
	ERROR_GET_TODO_BY_ID_FAILED          ErrorType = "ERROR_GET_TODO_BY_ID_FAILED"
	ERROR_GET_TODOS_FAILED               ErrorType = "ERROR_GET_TODOS_FAILED"

	// Users
	ERROR_CREATE_USER_PAYLOAD_IS_INVALID ErrorType = "ERROR_CREATE_USER_PAYLOAD_IS_INVALID"
	ERROR_CREATE_USER_FAILED             ErrorType = "ERROR_CREATE_USER_FAILED"
	ERROR_GET_CREATED_USER_FAILED        ErrorType = "ERROR_GET_CREATED_USER_FAILED"
	ERROR_DELETE_USER_NOT_EXIST          ErrorType = "ERROR_DELETE_USER_NOT_EXIST"
	ERROR_DELETE_USER_FAILED             ErrorType = "ERROR_DELETE_USER_FAILED"
	ERROR_GET_USER_FAILED                ErrorType = "ERROR_GET_USER_FAILED"

	// Auth
	ERROR_SIGN_IN_PAYLOAD_IS_INVALID   ErrorType = "ERROR_SIGN_IN_PAYLOAD_IS_INVALID"
	ERROR_SIGN_IN_FAILED               ErrorType = "ERROR_SIGN_IN_FAILED"
	ERROR_USER_TOKEN_IS_EXPIRED_FAILED ErrorType = "ERROR_USER_TOKEN_IS_EXPIRED_FAILED"
	ERROR_NOT_SIGN_IN_YET              ErrorType = "ERROR_NOT_SIGN_IN_YET"
	ERROR_TOKEN_PARSE_FAILED           ErrorType = "ERROR_TOKEN_PARSE_FAILED"
	ERROR_HASH_PASSWORD_FAILD          ErrorType = "ERROR_HASH_PASSWORD_FAILD"
)
